kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: database
    image: postgres:9-alpine

  - name: makoto
    image: elixir:1.9
    commands:
      - mix local.rebar --force
      - mix local.hex --force
      - mix deps.get
      - mix phx.digest
      - mix ecto.migrate
      - mix phx.server

services:
  - name: database
    image: postgres:9-alpine
    environment:
      POSTGRES_USER: optisite_user
      POSTGRES_PASSWORD: optisite_user_password
      POSTGRES_DB: optisite
