kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: discord-pre-build-notification
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: DISCORD_WEB_ID
      webhook_token:
        from_secret: DISCORD_WEB_TOKEN
      username: "Build"
      message: >
        `Build status: {{build.number}} run` \n
        `Repository: <https://git.optimine.com/{{ repo.owner }}/{{ repo.name }}>` \n
        `Duration: {{since build.started}}` \n
        `Commit: <https://git.optimine.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}>` \n
        `Branch: <https://git.optimine.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}>` \n
        `Author: {{ build.author }}` \n
        `Commit message: {{ build.message }}`

  - name: build
    image: docker.io/elixir:slim
    commands:
      - sh scripts/build.sh
    environment:
      MIX_ENV:
        from_secret: MIX_ENV
      SECRET_KEY_BASE:
        from_secret: SECRET_KEY_BASE

      MINECRAFT_DATABASE_URL:
        from_secret: MINECRAFT_DATABASE_URL
      DATABASE_URL:
        from_secret: DATABASE_URL
      HOST_URL:
        from_secret: HOST_URL

      RELAY_EMAIL:
        from_secret: RELAY_EMAIL
      USERNAME_EMAIL:
        from_secret: USERNAME_EMAIL
      PASSWORD_EMAIL:
        from_secret: PASSWORD_EMAIL

      CENT_APP_TOKEN:
        from_secret: CENT_APP_TOKEN
      CENT_APP_SHOP_ID:
        from_secret: CENT_APP_SHOP_ID
      # %%
      DISCORD_CLIENT_SECRET:
        from_secret: DISCORD_CLIENT_SECRET
      DISCORD_CLIENT_ID:
        from_secret: DISCORD_CLIENT_ID
      # %%
      RCON_HOST:
        from_secret: RCON_HOST
      RCON_PASSWORD:
        from_secret: RCON_PASSWORD
      RCON_PORT:
        from_secret: RCON_PORT
      # %%
      XENFORO_TOKEN:
        from_secret: XENFORO_TOKEN
      # %%
      MCTOP_TOKEN:
        from_secret: MCTOP_TOKEN
      TOPCRAFT_TOKEN:
        from_secret: TOPCRAFT_TOKEN
      SECRET_KEY:
        from_secret: SECRET_KEY
      API_SITE_TOKEN:
        from_secret: API_SITE_TOKEN

  - name: discord-post-build-notification
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: DISCORD_WEB_ID
      webhook_token:
        from_secret: DISCORD_WEB_TOKEN
      username: "Build"
      message: >
        {{#success build.status}}
         `Build status: {{build.number}} succeeded` \n
        {{else}}
          `Build status: {{build.number}} failed.` \n
        {{/success}}
        `Repository: <https://git.optimine.com/{{ repo.owner }}/{{ repo.name }}|{{ repo.name }}>` \n
        `Duration: {{since build.started}}` \n
        `Commit: <https://git.optimine.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>` \n
        `Branch: <https://git.optimine.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}>` \n
        `Author: {{ build.author }}` \n
        `Commit message: {{ build.message }}` \n

services:
  - name: database
    image: docker.io/postgres:14
    environment:
      POSTGRES_USER: optisite_user
      POSTGRES_PASSWORD: optisite_user_password
      POSTGRES_DB: optisite

  - name: database_maria
    image: docker.io/mariadb:10
    environment:
      MARIADB_USER: mc_general
      MARIADB_PASSWORD: test_password
      MARIADB_ROOT_PASSWORD: test_password_root
      MARIADB_DATABASE: mc_general

trigger:
  branch:
    - master
  event:
    - push
